workflows:
  android_release:
    name: Android Release (VideoSplitter)
    max_build_duration: 60

    environment:
      vars:
        RN_VERSION: "0.76.5"
      node: 20
      java: 17

    scripts:
      - name: Generate React Native project
        script: |
          npx @react-native-community/cli@latest init VideoSplitter --version $RN_VERSION --pm npm

      - name: Install dependencies (safe build)
        script: |
          cd VideoSplitter
          npm i react-native-document-picker react-native-fs

      - name: Rename app inside Android project
        script: |
          cd VideoSplitter/android/app/src/main/res/values
          # Replace default app_name in strings.xml
          sed -i 's/app_name">[^<]*/app_name">VideoSplitter/' strings.xml
          echo "✅ App name changed to VideoSplitter"

      - name: Copy your app code
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx VideoSplitter/App.tsx

      - name: Create JS bundle for release
        script: |
          cd VideoSplitter
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build Android release APK
        script: |
          cd VideoSplitter/android
          echo "android.buildToolsVersion=34.0.0" >> ../gradle.properties
          ./gradlew assembleRelease --no-daemon

      - name: Rename APK
        script: |
          cd VideoSplitter/android/app/build/outputs/apk/release
          mv app-release.apk VideoSplitter_v1_release.apk
          echo "✅ Release APK ready: VideoSplitter_v1_release.apk"

    artifacts:
      - VideoSplitter/android/app/build/outputs/apk/release/VideoSplitter_v1_release.apk

    publishing:
      email:
        recipients:
          - dehradunnn@gmail.com
        notify:
          success: true
          failure: true
