workflows:
  android_debug:
    name: Android Debug (React Native + FFmpegKit)
    max_build_duration: 60

    environment:
      groups:
        - github-secrets     # 👈 loads your GITHUB_TOKEN from the variable group
      vars:
        RN_VERSION: "0.76.5"
      node: 20
      java: 17

    scripts:
      - name: Generate React Native project (new CLI)
        script: |
          npx @react-native-community/cli@latest init OfflineVideoEditor --version $RN_VERSION --pm npm

      - name: Install dependencies (FFmpeg + pickers)
        script: |
          cd OfflineVideoEditor
          npm i ffmpeg-kit-react-native react-native-document-picker react-native-fs

      - name: Copy our app code into the project
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx OfflineVideoEditor/App.tsx

      - name: Enable FFmpegKit minimal package
        script: |
          cd OfflineVideoEditor/android
          echo "ffmpegKitPackage=min" >> ../gradle.properties

      - name: Patch Gradle repositories with GitHub auth
        script: |
          cd OfflineVideoEditor/android
          echo "
          allprojects {
              repositories {
                  maven {
                      url 'https://maven.pkg.github.com/arthenica/ffmpeg-kit'
                      credentials {
                          username = 'x-access-token'
                          password = System.getenv('GITHUB_TOKEN')
                      }
                  }
                  mavenCentral()
                  google()
              }
          }" >> build.gradle

      - name: Build Android debug APK
        script: |
          cd OfflineVideoEditor/android
          # Force stable SDK Build Tools version to avoid broken 35.0.0
          echo "android.buildToolsVersion=34.0.0" >> ../gradle.properties
          ./gradlew assembleDebug

      - name: Rename APK for easier identification
        script: |
          cd OfflineVideoEditor/android/app/build/outputs/apk/debug
          mv app-debug.apk OfflineVideoEditor_v1.apk
          echo "✅ APK renamed to OfflineVideoEditor_v1.apk"

    artifacts:
      - OfflineVideoEditor/android/app/build/outputs/apk/debug/OfflineVideoEditor_v1.apk

    publishing:
      email:
        recipients:
          - dehradunnn@gmail.com
        notify:
          success: true
          failure: true
