workflows:
  android_debug:
    name: Android Debug (React Native + FFmpegKit)
    max_build_duration: 60
    environment:
      vars:
        RN_VERSION: "0.76.5"
      node: 18
      java: 17
    scripts:
      - name: Generate React Native project
        script: |
          npx react-native@latest init OfflineVideoEditor --version $RN_VERSION --pm npm
      - name: Install dependencies (FFmpeg + pickers)
        script: |
          cd OfflineVideoEditor
          npm i ffmpeg-kit-react-native react-native-document-picker react-native-fs
      - name: Copy our app code into the project
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx OfflineVideoEditor/App.tsx
      - name: Patch Gradle to add FFmpegKit Maven repo
        script: |
          cd OfflineVideoEditor/android
          echo "Patching Gradle build file to add FFmpegKit Maven repo..."
          sed -i '/allprojects {/a\
              repositories {\
                  maven { url \"https://maven.pkg.github.com/arthenica/ffmpeg-kit\" }\
              }' build.gradle
      - name: Build Android debug APK
        script: |
          cd OfflineVideoEditor/android
          ./gradlew assembleDebug
    artifacts:
      - OfflineVideoEditor/android/app/build/outputs/apk/debug/app-debug.apk
