workflows:
  android_debug:
    name: Android Debug (React Native Clean Build)
    max_build_duration: 60

    environment:
      vars:
        RN_VERSION: "0.76.5"
      node: 20
      java: 17

    scripts:
      - name: Generate React Native project
        script: |
          npx @react-native-community/cli@latest init OfflineVideoEditor --version $RN_VERSION --pm npm

      - name: Install dependencies (basic)
        script: |
          cd OfflineVideoEditor
          npm i react-native-document-picker react-native-fs
          npm i

      - name: Copy your app code
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx OfflineVideoEditor/App.tsx

      - name: Patch Gradle repositories
        script: |
          cd OfflineVideoEditor/android
          echo "
          allprojects {
              repositories {
                  mavenCentral()
                  google()
                  maven { url 'https://www.jitpack.io' }
              }
          }" >> build.gradle

      - name: Build Android debug APK
        script: |
          cd OfflineVideoEditor/android
          # Force stable build tools
          echo "android.buildToolsVersion=34.0.0" >> ../gradle.properties
          ./gradlew assembleDebug --stacktrace

      - name: Rename APK
        script: |
          cd OfflineVideoEditor/android/app/build/outputs/apk/debug
          mv app-debug.apk OfflineVideoEditor_v1.apk
          echo "✅ APK created: OfflineVideoEditor_v1.apk"

    artifacts:
      - OfflineVideoEditor/android/app/build/outputs/apk/debug/OfflineVideoEditor_v1.apk

    publishing:
      email:
        recipients:
          - dehradunnn@gmail.com
        notify:
          success: true
          failure: true
