workflows:
  android_debug:
    name: Android Debug (React Native + FFmpegKit)
    max_build_duration: 60

    environment:
      vars:
        RN_VERSION: "0.76.5"
      node: 20
      java: 17

    scripts:
      - name: Generate React Native project (new CLI)
        script: |
          npx @react-native-community/cli@latest init OfflineVideoEditor --version $RN_VERSION --pm npm

      - name: Install dependencies (FFmpeg + pickers)
        script: |
          cd OfflineVideoEditor
          npm i ffmpeg-kit-react-native react-native-document-picker react-native-fs
          # use lightweight https-min package from Maven Central
          echo "ffmpegKitPackage=https-min" >> ../gradle.properties

      - name: Copy our app code into the project
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx OfflineVideoEditor/App.tsx

      - name: Patch Gradle repositories (Maven Central only)
        script: |
          cd OfflineVideoEditor/android
          echo "
          allprojects {
              repositories {
                  mavenCentral()
                  google()
                  maven { url 'https://www.jitpack.io' }
              }
          }" >> build.gradle

      - name: Build Android debug APK
        script: |
          cd OfflineVideoEditor/android
          # Force stable SDK Build Tools version
          echo "android.buildToolsVersion=34.0.0" >> ../gradle.properties
          ./gradlew assembleDebug

      - name: Rename APK for easier identification
        script: |
          cd OfflineVideoEditor/android/app/build/outputs/apk/debug
          mv app-debug.apk OfflineVideoEditor_v1.apk
          echo "✅ APK renamed to OfflineVideoEditor_v1.apk"

    artifacts:
      - OfflineVideoEditor/android/app/build/outputs/apk/debug/OfflineVideoEditor_v1.apk

    publishing:
      email:
        recipients:
          - dehradunnn@gmail.com
        notify:
          success: true
          failure: true
