workflows:
  android_release:
    name: Android Release (VideoSplitter + FFmpegKit)
    max_build_duration: 60

    environment:
      vars:
        RN_VERSION: "0.76.5"
        JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
      node: 20
      java: 17
      secure: true

    scripts:
      - name: Debug token check
        script: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "❌ GITHUB_TOKEN is missing!"
            exit 1
          else
            echo "✅ GITHUB_TOKEN found (length: ${#GITHUB_TOKEN})"
          fi

      - name: Generate React Native project
        script: |
          npx @react-native-community/cli@latest init VideoSplitter --version $RN_VERSION --pm npm

      - name: Install dependencies (FFmpeg + tools)
        script: |
          cd VideoSplitter
          npm i ffmpeg-kit-react-native react-native-document-picker react-native-fs

      - name: Rename app inside Android project
        script: |
          cd VideoSplitter/android/app/src/main/res/values
          sed -i 's/app_name">[^<]*/app_name">VideoSplitter/' strings.xml
          echo "✅ App name changed to VideoSplitter"

      - name: Copy your app code
        script: |
          cd $CM_BUILD_DIR
          cp app/App.tsx VideoSplitter/App.tsx

      - name: Create JS bundle for release
        script: |
          cd VideoSplitter
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Patch Gradle repositories with GitHub access
        script: |
          cd VideoSplitter/android
          echo "
          allprojects {
              repositories {
                  maven {
                      url 'https://maven.pkg.github.com/arthenica/ffmpeg-kit'
                      credentials {
                          username = 'x-access-token'
                          password = System.getenv('GITHUB_TOKEN')
                      }
                  }
                  mavenCentral()
                  google()
                  maven { url 'https://www.jitpack.io' }
              }
          }" >> build.gradle
          echo "✅ Gradle repo patched for FFmpegKit access"

      - name: Build Android release APK
        script: |
          cd VideoSplitter/android
          echo "android.buildToolsVersion=34.0.0" >> ../gradle.properties
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Rename APK
        script: |
          cd VideoSplitter/android/app/build/outputs/apk/release
          mv app-release.apk VideoSplitter_v1_release.apk
          echo "✅ Release APK ready: VideoSplitter_v1_release.apk"

    artifacts:
      - VideoSplitter/android/app/build/outputs/apk/release/VideoSplitter_v1_release.apk

    publishing:
      email:
        recipients:
          - dehradunnn@gmail.com
        notify:
          success: true
          failure: true
